use QLBHSieuThi
Go

create table USERS(
	USERNAME varchar(40) primary key,
	PASS varchar(30),
	HOTEN NVARCHAR(50),
	GIOITINH NVARCHAR(6) CHECK (GIOITINH='Nam' OR GIOITINH='Nữ'), 
	EMAIL varchar(50) UNIQUE,
	QUYEN int check(QUYEN=1 or QUYEN=0),--PHÂN QUYỀN VỚI ADMIN VÀ KHÁCH HÀNG
)
CREATE TABLE DONHANG(
	MADONHANG VARCHAR(8) PRIMARY KEY,
	USERNAME VARCHAR(40) REFERENCES USERS(USERNAME),
	TENDONHANG NVARCHAR(30),
	MAKHUYENMAI VARCHAR(8) REFERENCES KHUYENMAI(MAKHUYENMAI),
	HOTENNGUOIMUA NVARCHAR(50) REFERENCES USERS(HOTEN),
	XACNHAN INT CHECK (XACNHAN>=0 AND XACNHAN<=2) DEFAULT 0, --ĐƠN HÀNG ĐƯỢC ADMIN DUYỆT=1, CHƯA DUYỆT =0, ĐÃ GIAO =2
	NGAYDAT DATE,
	NGAYGIAOHANG DATE,
	
)
CREATE TABLE HANGHOA(
	MASANPHAM VARCHAR(8) PRIMARY KEY,
	MADONHANG VARCHAR(8) REFERENCES DONHANG(MADONHANG), --NULL
	TENSANPHAM NVARCHAR(50),
	SOLUONG INT,
	GIANHAPVAO INT,
	GIABANRA INT,
	NGAYNHAP DATE,
	KIEMTRALOI INT CHECK (KIEMTRALOI=0 OR KIEMTRALOI=1),--KIỂM TRA SẢN PHẨM LỖI HAY K
)
CREATE TABLE KHUYENMAI(
	MAKHUYENMAI VARCHAR(8) PRIMARY KEY,
	TENKHUYENMAI NVARCHAR(30),
	PHANTRAM INT CHECK (PHANTRAM>=0 AND PHANTRAM<=100),
	NGAYKHUYENMAI DATE,
)
